### PR TITLE
Fix heading turn into list

### LINKED ISSUE #194: Heading turns into a list when adding 1. + space
This should not be the behavior. Instead, 

https://github.com/hyvor/HyvorBlogs/assets/44988673/e4092d10-65bf-49d5-b648-5fd7ad2c37d6

### PR DESCRIPTION
**Pull request by Nolab0**
[Screencast from 2023-07-03 10-58-49.webm](https://github.com/hyvor/HyvorBlogs/assets/88531865/ea8bd233-0331-4c3c-a267-706cdb00a099)

### CODE REVIEW

File: resources/js/console/Posts/Post/ProseMirror/schema.ts [hunk 1]
```diff
@@ -316,6 +316,6 @@ export const marks = {
 const schemaWithoutList = new Schema({nodes, marks})
 
 export default new Schema({
-    nodes: addListNodes(schemaWithoutList.spec.nodes, "block+", "block"),
+    nodes: addListNodes(schemaWithoutList.spec.nodes, "paragraph+", "block"),
```
Comment (supun-io) [inline resources/js/console/Posts/Post/ProseMirror/schema.ts]: This fix is not good. This essentially changes the content allowed in list items. 

This will no longer allow images or any other node inside list items.

The fix should only change the keymap handler to prevent tunning headings into lists.
